In [8]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [4]:
odd_number_list = [1, 3, 5, 7]


In [5]:
np.array(odd_number_list)

array([1, 3, 5, 7])

In [7]:
two_dim_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
np.array(two_dim_list)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [9]:
np.random.rand(3, 4)

array([[0.11786959, 0.07482373, 0.07856392, 0.83390083],
       [0.72161587, 0.48772791, 0.9913717 , 0.97611781],
       [0.72163709, 0.52932936, 0.45999308, 0.32113847]])

1.Создать массив из списка,состоящего из чисел от 0 до 9 при помощи функций array() из модуля numpy

In [17]:
import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2.Создайте массив состоящий из нечетных чисел от 1 до 19 при помощи ф-ции arange()

In [20]:
import numpy as np
array = np.arange(1, 19)
array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

3.Создайте массив состоящий из двадцати нолей

In [22]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

4. Создайте двумерный массив ,состоящий из 20 единиц в котором 5 строк и 4 столбца

In [28]:
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

5.Создать массив состоящий из 5 равномерно распределенных чисел от 3 до 7

In [31]:
np.linspace(3, 7, 5)



array([3., 4., 5., 6., 7.])

6.Создайте 2х мерный массив состоящий из 9 равномерно распределенных чисел от 3 до 7

In [40]:
np.linspace(3, 7, 9).reshape(3, 3)

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5],
       [6. , 6.5, 7. ]])

7.Создайте массив,состоящий из 10 случайных целых чисел из диапазона от 1 до 100 
и присвойте его максимальное значение переменной max_number и выведите значение 
этой переменной при помощи функции print()

In [47]:
max_number = np.random.randint(1, 100, 10)
print(max_number.max())

91


In [48]:
max_number = np.random.randint(1, 101, 10).max()

print(max_number)

87
