1.Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20, затем создайте массив состоящий из 5 элементов, начиная со 2 по порядку. Выведите значения обоих массивов при помощи функции print()

In [1]:
import numpy as np

In [7]:
arr = np.random.randint(1, 21, 10)
arr

array([10, 15,  5,  2, 16, 14, 15,  9,  2, 14])

In [9]:
new_arr = arr[1:6]
print(arr)
print(new_arr)

[10 15  5  2 16 14 15  9  2 14]
[15  5  2 16 14]


2.Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 0 до 20, затем создайте массив состоящий из элементов, начиная с третьего по порядку до последнего. Выведите значения обоих массивов при помощи функции print()

In [11]:
arr = np.random.randint(0, 21, 10)
new_arr = arr[2:]
print(arr)
print(new_arr)

[18 13  6 18  7 15 16  4 17  2]
[ 6 18  7 15 16  4 17  2]


3.Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца. Затем создайте массив состоящий из элементов , второй и третьей строки и первого и второго столбца по порядку. Выведите значения обоих массивов при помощи функции print()

In [20]:
two_dim_arr = np.random.randint(3, 12, 12).reshape(4, 3)
two_dim_arr

array([[11, 11,  3],
       [ 8, 10,  9],
       [ 6,  4,  6],
       [10,  7,  9]])

In [24]:
new_two_dim_arr = two_dim_arr[1:3, :2]
new_two_dim_arr
print(two_dim_arr)
print(new_two_dim_arr)

[[11 11  3]
 [ 8 10  9]
 [ 6  4  6]
 [10  7  9]]
[[ 8 10]
 [ 6  4]]


4.Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 0 до 9, в котором 4 строки и 6 столбцов. Затем создайте массив состоящий из элементов , которые больше числа 3. Выведите значения обоих массивов при помощи функции print()

In [30]:
two_dim_arr = np.random.randint(0, 10, 24).reshape(4, 6)
new_two_dim_arr = two_dim_arr[two_dim_arr > 3] 
print(two_dim_arr)
print(new_two_dim_arr)


[[6 8 0 8 4 7]
 [8 7 8 4 1 8]
 [5 0 4 3 8 2]
 [2 0 0 8 4 7]]
[6 8 8 4 7 8 7 8 4 8 5 4 8 8 4 7]


ОПЕРАЦИИ c массивами

1.Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20,
затем создайте массив состоящий из 10 элементов, начиная с 2. Выведите значения этих массивов,
а также их сумму, при помощи функции print()

In [36]:
arr = np.random.randint(1, 21, 10)
new_arr = np.arange(2, 12)
print(arr)
print(new_arr)
print(arr + new_arr)

[ 3 19 11  1  8 20 10 18 14 11]
[ 2  3  4  5  6  7  8  9 10 11]
[ 5 22 15  6 14 27 18 27 24 22]


2.Создайте массив , состоящий из 7 случайных целых чисел из диапазона от 0 до 9, затем создайте новый массив состоящий из 7 элементов первого массива, увеличенных в 3 раза. Выведите значения этих массивов при помощи функции print()

In [38]:
arr = np.random.randint(0, 10, 7)
new_arr = arr * 3
print(arr)
print(new_arr)

[2 6 2 3 9 1 5]
[ 6 18  6  9 27  3 15]


3.Создайте массив состоящий из квадратных корней 20 элементов по порядку, начиная с 7.
Выведите значение массива при помощи функции print()

In [39]:
arr = np.sqrt(np.arange(7, 27))

print(arr)

[2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951]
